#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 31 15:00:45 2022

@author: jorge

This script takes as input the xlsx files generated by mut_screening_8.py and rename_genes.py
and merges all the information to represent a single heatmap showing the information
relative to the Klebsiella samples in all experimental groups.

"""

import os
import pandas as pd
from functools import reduce
import seaborn as sb
from matplotlib import pyplot

DirName = "/home/jorge/Documents/TFM/clinical_samples/R_analysis/all_mutations_heatmaps_renamed"

files = os.listdir(DirName)

df_list = []

for file in files:
    file_whole = DirName + "/" + file
    strain_name = file.split("_")[0]
    strain = pd.read_excel(file_whole)
    if "CF" not in strain_name:
        df_list.append(strain)
    
#pd.concat([df.set_index])

"""
for df in df_list:
    #df.index = df["genes"]
    #df = df.drop("genes", axis = 1)
    print(df)"""

    
merged_df = reduce(lambda  left,right: pd.merge(left,right,on=['genes'],
                                            how='outer'), df_list)

merged_df.index = merged_df["genes"]
merged_df = merged_df.drop("genes", axis = 1)

column_names = ["pOXA-48_1_H53", "pOXA-48_2_H53", "pOXA-48_3_H53",
                "pOXA-48_1_K163", "pOXA-48_2_K163", "pOXA-48_3_K163",
                "pOXA-48_1_K091", "pOXA-48_2_K091", "pOXA-48_3_K091",
                "pOXA-48_1_K209", "pOXA-48_2_K209", "pOXA-48_3_K209",
                "pOXA-48_1_K147", "pOXA-48_2_K147", "pOXA-48_3_K147",
                "pOXA-48_1_K153", "pOXA-48_2_K153", "pOXA-48_3_K153",
                "pOXA-48+Ab_1_H53", "pOXA-48+Ab_2_H53", "pOXA-48+Ab_3_H53",
                "pOXA-48+Ab_1_K163", "pOXA-48+Ab_2_K163", "pOXA-48+Ab_3_K163",
                "pOXA-48+Ab_1_K091", "pOXA-48+Ab_2_K091", "pOXA-48+Ab_3_K091",
                "pOXA-48+Ab_1_K209", "pOXA-48+Ab_2_K209", "pOXA-48+Ab_3_K209",
                "pOXA-48+Ab_1_K147", "pOXA-48+Ab_2_K147", "pOXA-48+Ab_3_K147",
                "pOXA-48+Ab_1_K153", "pOXA-48+Ab_2_K153", "pOXA-48+Ab_3_K153",
                "no pOXA-48_1_H53", "no pOXA-48_2_H53", "no pOXA-48_3_H53",
                "no pOXA-48_1_K163", "no pOXA-48_2_K163", "no pOXA-48_3_K163",
                "no pOXA-48_1_K091", "no pOXA-48_2_K091", "no pOXA-48_3_K091",
                "no pOXA-48_1_K209", "no pOXA-48_2_K209", "no pOXA-48_3_K209",
                "no pOXA-48_1_K147", "no pOXA-48_2_K147", "no pOXA-48_3_K147",
                "no pOXA-48_1_K153", "no pOXA-48_2_K153", "no pOXA-48_3_K153"]

merged_df = merged_df.reindex(columns=column_names)

merged_df = merged_df.drop("pOXA-48_3_K147", axis = 1)
merged_df = merged_df.drop("pOXA-48+Ab_1_K163", axis = 1)

merged_df = merged_df.fillna(0)

# reshape dataframe to show SNPs and NJ evidences separately

rownames = list(merged_df.index.values)

snp_list = []
nj_list = []

for gene in rownames:
    if "←" in gene or "→" in gene or "*" in gene:
        snp_list.append(gene)
    else:
        nj_list.append(gene)

new_rownames = nj_list + snp_list

merged_df = merged_df.reindex(new_rownames, axis = 0)

pyplot.figure(figsize=(100, 290)) # dimensions of plot may vary depending on the number of genes mutated
heatmap = sb.heatmap(merged_df, cmap="BuPu", xticklabels=True, yticklabels=True, vmax = 100)
heatmap.set_xticklabels(heatmap.get_xticklabels(),rotation = 60, horizontalalignment='right', fontsize = 26)
heatmap.set_yticklabels(heatmap.get_ymajorticklabels(), fontsize = 22)

# filtering by those which only appear at frequencies higher than 25%

merged_df_filt = merged_df

merged_df.to_excel("/home/jorge/Documents/TFM/clinical_samples/R_analysis/all_mutations_heatmaps/whole_v_call_merged.xlsx")

for index, row in merged_df.iterrows():
    if row[0] < 25 and row[1] < 25 and row[2] < 25 and row[3] < 25 and row[4] < 25 and row[5] < 25 and row[6] < 25 and row[7] < 25 and row[8] < 25 and row[9] < 25 and row[10] < 25 and row[11] < 25 and row[12] < 25 and row[13] < 25 and row[14] < 25 and row[15] < 25 and row[16] < 25 and row[17] < 25 and row[18] < 25 and row[19] < 25 and row[20] < 25 and row[21] < 25 and row[22] < 25 and row[23] < 25 and row[24] < 25 and row[25] < 25 and row[26] < 25 and row[27] < 25 and row[28] < 25 and row[29] < 25 and row[30] < 25 and row[31] < 25 and row[32] < 25:
        merged_df_filt = merged_df_filt.drop(index)

# this makes it go from 680 to 124 genes

# print(merged_df)

pyplot.figure(figsize=(100, 90)) # dimensions of plot may vary depending on the number of genes mutated
heatmap = sb.heatmap(merged_df_filt, cmap="BuPu", xticklabels=True, yticklabels=True, vmax = 100)
heatmap.set_xticklabels(heatmap.get_xticklabels(),rotation = 60, horizontalalignment='right', fontsize = 26)
heatmap.set_yticklabels(heatmap.get_ymajorticklabels(), fontsize = 22)


# Get heatmap with mutations only present in presence of pOXA-48

parsed_merged_df = merged_df

for index, row in parsed_merged_df.iterrows():
    if row[34] != 0 or row[35] != 0 or row[36] != 0 or row[37] != 0 or row[38] != 0 or row[39] != 0 or row[40] != 0 or row[41] != 0 or row[42] != 0 or row[43] != 0 or row[44] != 0 or row[45] != 0 or row[46] != 0 or row[47] != 0 or row[48] != 0 or row[49] != 0 or row[50] != 0 or row[51] != 0:
        parsed_merged_df = parsed_merged_df.drop(index)
        
# As the resulting dataframe contains 342 genes, filter out those which appear
# with mutation frequencies lower than 25%

for index, row in parsed_merged_df.iterrows():
    if row[0] < 25 and row[1] < 25 and row[2] < 25 and row[3] < 25 and row[4] < 25 and row[5] < 25 and row[6] < 25 and row[7] < 25 and row[8] < 25 and row[9] < 25 and row[10] < 25 and row[11] < 25 and row[12] < 25 and row[13] < 25 and row[14] < 25 and row[15] < 25 and row[16] < 25 and row[17] < 25 and row[18] < 25 and row[19] < 25 and row[20] < 25 and row[21] < 25 and row[22] < 25 and row[23] < 25 and row[24] < 25 and row[25] < 25 and row[26] < 25 and row[27] < 25 and row[28] < 25 and row[29] < 25 and row[30] < 25 and row[31] < 25 and row[32] < 25:
        parsed_merged_df = parsed_merged_df.drop(index)
        
# this results in a dataframe of 62 mutated genes

pyplot.figure(figsize=(100, 45)) # dimensions of plot may vary depending on the number of genes mutated
heatmap = sb.heatmap(parsed_merged_df, cmap="BuPu", xticklabels=True, yticklabels=True, vmax = 100)
heatmap.set_xticklabels(heatmap.get_xticklabels(),rotation = 60, horizontalalignment='right', fontsize = 26)
heatmap.set_yticklabels(heatmap.get_ymajorticklabels(), fontsize = 22)

